plugins {
    id 'com.android.application'
}

android {
    namespace 'it.andrea.telecomandotv'
    compileSdk 34

    defaultConfig {
        applicationId 'it.andrea.telecomandotv'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            // firmata con la chiave di debug: basta per installarla sul proprio telefono
            signingConfig signingConfigs.debug
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
